package com.zhou.model;

import java.util.Date;

public class Contract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.useraid
     *
     * @mbggenerated
     */
    private Integer useraid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.useraname
     *
     * @mbggenerated
     */
    private String useraname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.userbid
     *
     * @mbggenerated
     */
    private Integer userbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.userbname
     *
     * @mbggenerated
     */
    private String userbname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.starttime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.houseid
     *
     * @mbggenerated
     */
    private Integer houseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.ispassed
     *
     * @mbggenerated
     */
    private Integer ispassed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.ispayed
     *
     * @mbggenerated
     */
    private Boolean ispayed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.endtime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.totalprice
     *
     * @mbggenerated
     */
    private Integer totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.createdat
     *
     * @mbggenerated
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.id
     *
     * @return the value of contract.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.id
     *
     * @param id the value for contract.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.useraid
     *
     * @return the value of contract.useraid
     *
     * @mbggenerated
     */
    public Integer getUseraid() {
        return useraid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.useraid
     *
     * @param useraid the value for contract.useraid
     *
     * @mbggenerated
     */
    public void setUseraid(Integer useraid) {
        this.useraid = useraid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.useraname
     *
     * @return the value of contract.useraname
     *
     * @mbggenerated
     */
    public String getUseraname() {
        return useraname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.useraname
     *
     * @param useraname the value for contract.useraname
     *
     * @mbggenerated
     */
    public void setUseraname(String useraname) {
        this.useraname = useraname == null ? null : useraname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.userbid
     *
     * @return the value of contract.userbid
     *
     * @mbggenerated
     */
    public Integer getUserbid() {
        return userbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.userbid
     *
     * @param userbid the value for contract.userbid
     *
     * @mbggenerated
     */
    public void setUserbid(Integer userbid) {
        this.userbid = userbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.userbname
     *
     * @return the value of contract.userbname
     *
     * @mbggenerated
     */
    public String getUserbname() {
        return userbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.userbname
     *
     * @param userbname the value for contract.userbname
     *
     * @mbggenerated
     */
    public void setUserbname(String userbname) {
        this.userbname = userbname == null ? null : userbname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.starttime
     *
     * @return the value of contract.starttime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.starttime
     *
     * @param starttime the value for contract.starttime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.houseid
     *
     * @return the value of contract.houseid
     *
     * @mbggenerated
     */
    public Integer getHouseid() {
        return houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.houseid
     *
     * @param houseid the value for contract.houseid
     *
     * @mbggenerated
     */
    public void setHouseid(Integer houseid) {
        this.houseid = houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.ispassed
     *
     * @return the value of contract.ispassed
     *
     * @mbggenerated
     */
    public Integer getIspassed() {
        return ispassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.ispassed
     *
     * @param ispassed the value for contract.ispassed
     *
     * @mbggenerated
     */
    public void setIspassed(Integer ispassed) {
        this.ispassed = ispassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.ispayed
     *
     * @return the value of contract.ispayed
     *
     * @mbggenerated
     */
    public Boolean getIspayed() {
        return ispayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.ispayed
     *
     * @param ispayed the value for contract.ispayed
     *
     * @mbggenerated
     */
    public void setIspayed(Boolean ispayed) {
        this.ispayed = ispayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.endtime
     *
     * @return the value of contract.endtime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.endtime
     *
     * @param endtime the value for contract.endtime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.totalprice
     *
     * @return the value of contract.totalprice
     *
     * @mbggenerated
     */
    public Integer getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.totalprice
     *
     * @param totalprice the value for contract.totalprice
     *
     * @mbggenerated
     */
    public void setTotalprice(Integer totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.createdat
     *
     * @return the value of contract.createdat
     *
     * @mbggenerated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.createdat
     *
     * @param createdat the value for contract.createdat
     *
     * @mbggenerated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.info
     *
     * @return the value of contract.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.info
     *
     * @param info the value for contract.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}