package com.zhou.model;

import java.util.Date;

public class House {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.postion
     *
     * @mbggenerated
     */
    private String postion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.ownername
     *
     * @mbggenerated
     */
    private String ownername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.ownerid
     *
     * @mbggenerated
     */
    private Integer ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.isborrowed
     *
     * @mbggenerated
     */
    private Boolean isborrowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.isempty
     *
     * @mbggenerated
     */
    private Integer isempty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.borrowerid
     *
     * @mbggenerated
     */
    private String borrowerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.borrowertime
     *
     * @mbggenerated
     */
    private Date borrowertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.returntime
     *
     * @mbggenerated
     */
    private Date returntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.createdat
     *
     * @mbggenerated
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column houses.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.id
     *
     * @return the value of houses.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.id
     *
     * @param id the value for houses.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.avatar
     *
     * @return the value of houses.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.avatar
     *
     * @param avatar the value for houses.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.name
     *
     * @return the value of houses.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.name
     *
     * @param name the value for houses.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.size
     *
     * @return the value of houses.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.size
     *
     * @param size the value for houses.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.type
     *
     * @return the value of houses.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.type
     *
     * @param type the value for houses.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.postion
     *
     * @return the value of houses.postion
     *
     * @mbggenerated
     */
    public String getPostion() {
        return postion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.postion
     *
     * @param postion the value for houses.postion
     *
     * @mbggenerated
     */
    public void setPostion(String postion) {
        this.postion = postion == null ? null : postion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.ownername
     *
     * @return the value of houses.ownername
     *
     * @mbggenerated
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.ownername
     *
     * @param ownername the value for houses.ownername
     *
     * @mbggenerated
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername == null ? null : ownername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.ownerid
     *
     * @return the value of houses.ownerid
     *
     * @mbggenerated
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.ownerid
     *
     * @param ownerid the value for houses.ownerid
     *
     * @mbggenerated
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.isborrowed
     *
     * @return the value of houses.isborrowed
     *
     * @mbggenerated
     */
    public Boolean getIsborrowed() {
        return isborrowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.isborrowed
     *
     * @param isborrowed the value for houses.isborrowed
     *
     * @mbggenerated
     */
    public void setIsborrowed(Boolean isborrowed) {
        this.isborrowed = isborrowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.isempty
     *
     * @return the value of houses.isempty
     *
     * @mbggenerated
     */
    public Integer getIsempty() {
        return isempty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.isempty
     *
     * @param isempty the value for houses.isempty
     *
     * @mbggenerated
     */
    public void setIsempty(Integer isempty) {
        this.isempty = isempty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.borrowerid
     *
     * @return the value of houses.borrowerid
     *
     * @mbggenerated
     */
    public String getBorrowerid() {
        return borrowerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.borrowerid
     *
     * @param borrowerid the value for houses.borrowerid
     *
     * @mbggenerated
     */
    public void setBorrowerid(String borrowerid) {
        this.borrowerid = borrowerid == null ? null : borrowerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.borrowertime
     *
     * @return the value of houses.borrowertime
     *
     * @mbggenerated
     */
    public Date getBorrowertime() {
        return borrowertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.borrowertime
     *
     * @param borrowertime the value for houses.borrowertime
     *
     * @mbggenerated
     */
    public void setBorrowertime(Date borrowertime) {
        this.borrowertime = borrowertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.returntime
     *
     * @return the value of houses.returntime
     *
     * @mbggenerated
     */
    public Date getReturntime() {
        return returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.returntime
     *
     * @param returntime the value for houses.returntime
     *
     * @mbggenerated
     */
    public void setReturntime(Date returntime) {
        this.returntime = returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.price
     *
     * @return the value of houses.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.price
     *
     * @param price the value for houses.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.createdat
     *
     * @return the value of houses.createdat
     *
     * @mbggenerated
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.createdat
     *
     * @param createdat the value for houses.createdat
     *
     * @mbggenerated
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column houses.info
     *
     * @return the value of houses.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column houses.info
     *
     * @param info the value for houses.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}